"""created gurupreet_expense table

Revision ID: 34c30c58aa7d
Revises: 30d5be75d7ed
Create Date: 2026-03-18 15:28:27.429916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34c30c58aa7d'
down_revision: Union[str, Sequence[str], None] = '30d5be75d7ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gurupreet_expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('expense_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gurupreet_expense_id'), 'gurupreet_expense', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gurupreet_expense_id'), table_name='gurupreet_expense')
    op.drop_table('gurupreet_expense')
    # ### end Alembic commands ###
