"""added chat_id column in the users table

Revision ID: 7099ad297d12
Revises: 88484834012e
Create Date: 2026-03-29 12:14:01.459421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7099ad297d12'
down_revision: Union[str, Sequence[str], None] = '88484834012e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('chat_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'chat_id')
    # ### end Alembic commands ###
