"""renamed user column from expenses table to title

Revision ID: 87b1b07f527f
Revises: 7099ad297d12
Create Date: 2026-04-08 17:26:55.944354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87b1b07f527f'
down_revision: Union[str, Sequence[str], None] = '7099ad297d12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('title', sa.String(), nullable=False))
    op.drop_column('expenses', 'user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('user', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('expenses', 'title')
    # ### end Alembic commands ###
