"""removed url column

Revision ID: 92f964cb9d04
Revises: ad9828b8220e
Create Date: 2026-03-17 22:33:23.242992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92f964cb9d04'
down_revision: Union[str, Sequence[str], None] = 'ad9828b8220e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
