"""added file_type column in files table

Revision ID: 9cf0140b41c6
Revises: 76c97389f209
Create Date: 2026-03-17 13:00:38.499438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cf0140b41c6'
down_revision: Union[str, Sequence[str], None] = '76c97389f209'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('file_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'file_type')
    # ### end Alembic commands ###
