"""file_secret_id to file_unique_id

Revision ID: ad9828b8220e
Revises: 9cf0140b41c6
Create Date: 2026-03-17 13:08:40.084639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad9828b8220e'
down_revision: Union[str, Sequence[str], None] = '9cf0140b41c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('file_unique_id', sa.String(), nullable=True))
    op.drop_column('files', 'file_secret_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('file_secret_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('files', 'file_unique_id')
    # ### end Alembic commands ###
